/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateReplyArgs } from "./CreateReplyArgs";
import { UpdateReplyArgs } from "./UpdateReplyArgs";
import { DeleteReplyArgs } from "./DeleteReplyArgs";
import { ReplyFindManyArgs } from "./ReplyFindManyArgs";
import { ReplyFindUniqueArgs } from "./ReplyFindUniqueArgs";
import { Reply } from "./Reply";
import { ReplyService } from "../reply.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Reply)
export class ReplyResolverBase {
  constructor(
    protected readonly service: ReplyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Reply",
    action: "read",
    possession: "any",
  })
  async _repliesMeta(
    @graphql.Args() args: ReplyFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Reply])
  @nestAccessControl.UseRoles({
    resource: "Reply",
    action: "read",
    possession: "any",
  })
  async replies(@graphql.Args() args: ReplyFindManyArgs): Promise<Reply[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Reply, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Reply",
    action: "read",
    possession: "own",
  })
  async reply(
    @graphql.Args() args: ReplyFindUniqueArgs
  ): Promise<Reply | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Reply)
  @nestAccessControl.UseRoles({
    resource: "Reply",
    action: "create",
    possession: "any",
  })
  async createReply(@graphql.Args() args: CreateReplyArgs): Promise<Reply> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Reply)
  @nestAccessControl.UseRoles({
    resource: "Reply",
    action: "update",
    possession: "any",
  })
  async updateReply(
    @graphql.Args() args: UpdateReplyArgs
  ): Promise<Reply | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Reply)
  @nestAccessControl.UseRoles({
    resource: "Reply",
    action: "delete",
    possession: "any",
  })
  async deleteReply(
    @graphql.Args() args: DeleteReplyArgs
  ): Promise<Reply | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
